---
- name: set timezone
  copy: src=timezone
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
  notify:
    - update timezone

- name: install ntp
  apt: pkg=ntp state=latest update_cache=yes

- name: make sure ntp is running
  service: name=ntp state=running enabled=yes

# Flush handlers so that we can be sure the system uses the timezone from
# /etc/timezone (even if laters tasks fail)
- meta: flush_handlers
